#!/usr/bin/env python3
"""Update .codex/ALLOWED_SCOPE.txt for an approved task.

This helper is optional. Agent Memory Kit does not require Python.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

SAFE_DEFAULT = [
    "AGENTS.md",
    "PROJECT_AI_BRIEF.md",
    "docs/**",
    "Project Map/**",
]

DENY_PATTERNS = (
    ".git",
    ".env",
    "secret",
    "secrets",
    "credential",
    "credentials",
    "private_key",
    "id_rsa",
    "*.pem",
)


def validate_paths(paths: list[str], allow_broad: bool) -> list[str]:
    cleaned: list[str] = []
    for raw in paths:
        path = raw.strip().replace("\\", "/")
        if not path or path.startswith("#"):
            continue
        lower = path.lower()
        if path.startswith("/") or ":" in path[:3]:
            raise SystemExit(f"Refusing absolute path: {path}")
        if ".." in Path(path).parts:
            raise SystemExit(f"Refusing parent traversal: {path}")
        if any(token in lower for token in DENY_PATTERNS):
            raise SystemExit(f"Refusing sensitive path: {path}")
        if not allow_broad and path.endswith("/**") and path not in {"docs/**", "Project Map/**"}:
            raise SystemExit(f"Refusing broad write glob without --allow-broad: {path}")
        cleaned.append(path)
    if not cleaned:
        raise SystemExit("No valid paths supplied.")
    return cleaned


def write_scope(scope_file: Path, paths: list[str]) -> None:
    scope_file.parent.mkdir(parents=True, exist_ok=True)
    content = "# Generated by update_allowed_scope.py.\n# One allowed write path per line.\n\n" + "\n".join(paths) + "\n"
    scope_file.write_text(content, encoding="utf-8")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scope-file", default=".codex/ALLOWED_SCOPE.txt")
    parser.add_argument("--reset", action="store_true", help="reset to safe default")
    parser.add_argument("--allow-broad", action="store_true", help="allow broad globs such as Options_api/**")
    parser.add_argument("paths", nargs="*", help="allowed write paths")
    args = parser.parse_args(argv)

    scope_file = Path(args.scope_file)
    paths = SAFE_DEFAULT if args.reset else validate_paths(args.paths, args.allow_broad)
    write_scope(scope_file, paths)
    print(f"Wrote {scope_file}")
    for path in paths:
        print(f"- {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
